name: Build Squatch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-locale:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Build with ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.2
        target: esp32s2
        path: ./locale

  build-brain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build ROS2 Docker Image
      run: docker build ./brain
